<a href="https://colab.research.google.com/github/harshit-agarwal92/Data-Analysis/blob/main/data_loading_storage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA LOADING AND STORAGE**

In [63]:
import pandas as pd

In [64]:
import os

In [65]:
print(os.getcwd())
print(os.listdir())

/content
['.config', 'students_pkl.pkl', 'employess.tsv', 'employess.csv', 'employess.xlsx', 'student_ppt.parquet', 'students.csv', 'stduents.db', 'students.txt', 'sample_data']

In [66]:
csv_data = """Employee_ID,Name,Department,City,Salary
E101,Aman,IT,Mathura,55000
E102,Priya,HR,Agra,48000
E103,Kunal,Sales,Delhi,62000
E104,Nisha,IT,Noida,52000
E105,Rohan,Finance,Mathura,47000
E106,Sneha,HR,Agra,61000
E107,Vikas,Sales,Delhi,58000
"""

with open("employess.csv","w") as f:
    f.write(csv_data)
with open("employess.csv", "r") as f:
      csv_data=f.read()
print(csv_data)

Employee_ID,Name,Department,City,Salary
E101,Aman,IT,Mathura,55000
E102,Priya,HR,Agra,48000
E103,Kunal,Sales,Delhi,62000
E104,Nisha,IT,Noida,52000
E105,Rohan,Finance,Mathura,47000
E106,Sneha,HR,Agra,61000
E107,Vikas,Sales,Delhi,58000

In [67]:
#into excel
df = pd.read_csv("employess.csv")
df.to_excel("employess.xlsx", sheet_name="Employee_Data", index=False)


excel_df = pd.read_excel("employess.xlsx", sheet_name="Employee_Data")
print(excel_df)

  Employee_ID   Name Department     City  Salary
0        E101   Aman         IT  Mathura   55000
1        E102  Priya         HR     Agra   48000
2        E103  Kunal      Sales    Delhi   62000
3        E104  Nisha         IT    Noida   52000
4        E105  Rohan    Finance  Mathura   47000
5        E106  Sneha         HR     Agra   61000
6        E107  Vikas      Sales    Delhi   58000

In [68]:
#into tsv
df = pd.read_csv("employess.csv")
df.to_csv("employess.tsv", sep="\t", index=False)

tsv_df = pd.read_csv("employess.tsv", sep="\t")
print(tsv_df)

  Employee_ID   Name Department     City  Salary
0        E101   Aman         IT  Mathura   55000
1        E102  Priya         HR     Agra   48000
2        E103  Kunal      Sales    Delhi   62000
3        E104  Nisha         IT    Noida   52000
4        E105  Rohan    Finance  Mathura   47000
5        E106  Sneha         HR     Agra   61000
6        E107  Vikas      Sales    Delhi   58000

In [69]:
#identify the header row
with open("employess.csv", "r") as f:
   header_row = next(f)
print(header_row)
print("----------------------------------------------")
df = pd.read_csv("employess.csv", header=None)
print(df)
print("------------------------------------------------")

df.columns = ["ID", "Employee_Name", "Dept", "Location", "Monthly_Salary"]

print("\nUpdated Headers:", df.columns.tolist())

print("------------------------------------------------")
print(df.head())

Employee_ID,Name,Department,City,Salary

----------------------------------------------
             0      1           2        3       4
0  Employee_ID   Name  Department     City  Salary
1         E101   Aman          IT  Mathura   55000
2         E102  Priya          HR     Agra   48000
3         E103  Kunal       Sales    Delhi   62000
4         E104  Nisha          IT    Noida   52000
5         E105  Rohan     Finance  Mathura   47000
6         E106  Sneha          HR     Agra   61000
7         E107  Vikas       Sales    Delhi   58000
------------------------------------------------

Updated Headers: ['ID', 'Employee_Name', 'Dept', 'Location', 'Monthly_Salary']
------------------------------------------------
            ID Employee_Name        Dept Location Monthly_Salary
0  Employee_ID          Name  Department     City         Salary
1         E101          Aman          IT  Mathura          55000
2         E102         Priya          HR     Agra          48000
3         E103         Kunal       Sales    Delhi          62000
4         E104         Nisha          IT    Noida          52000

In [70]:
#create text file,data enter|write operation
with open("students.txt","w") as file:
  file.write("Name,Department,Marks,City\n"),
  file.write("Aastik,CSE,85,Agra\n"),
  file.write("Abhiyank,IT,88,Mathura\n"),
  file.write("Ishika,CSE,91,Aligarh\n"),
  file.write("Disha,CSE,99,Mathura\n"),
  file.write("Harshit,IT,100,Agra"),

#conversion of txt file into csv file

In [71]:
with open("students.txt","r") as file:
  data=file.read()
print(data)

Name,Department,Marks,City
Aastik,CSE,85,Agra
Abhiyank,IT,88,Mathura
Ishika,CSE,91,Aligarh
Disha,CSE,99,Mathura
Harshit,IT,100,Agra

In [72]:
import pandas as pd
df = pd.read_csv('students.txt')
df.to_csv('students.csv', index=True)
display(df)

       Name Department  Marks     City
0    Aastik        CSE     85     Agra
1  Abhiyank         IT     88  Mathura
2    Ishika        CSE     91  Aligarh
3     Disha        CSE     99  Mathura
4   Harshit         IT    100     Agra

In [73]:
#JSON,EXCEL,TSV

In [74]:
#pickel
df_pickle=pd.DataFrame({
    "Name":["Aastik","Abhiyank","Ishika","Disha","Harshit"],
    "Marks":[85,88,91,99,100]
})
df_pickle

       Name  Marks
0    Aastik     85
1  Abhiyank     88
2    Ishika     91
3     Disha     99
4   Harshit    100

In [75]:
#save the dataframe into pickle
df.to_pickle("students_pkl.pkl")

In [76]:
#read the pkl file
student_pkl = pd.read_pickle("students_pkl.pkl")
display(student_pkl)

       Name Department  Marks     City
0    Aastik        CSE     85     Agra
1  Abhiyank         IT     88  Mathura
2    Ishika        CSE     91  Aligarh
3     Disha        CSE     99  Mathura
4   Harshit         IT    100     Agra

# **WEB SCRAPPING**

In [77]:
import requests
from bs4 import BeautifulSoup
url="https://www.flipkart.com/"
page=requests.get(url)
soup=BeautifulSoup(page.text,"html.parser")
print(soup.title.text)

Online Shopping Site for Mobiles, Electronics, Furniture, Grocery, Lifestyle, Books & More. Best Offers!

In [78]:
url="https://www.dishaelectronics.in/"
page=requests.get(url)
soup=BeautifulSoup(page.text,"html.parser")
print(soup.title.text)

Disha Electronics : Engineers, Electrical Contractors and Consultants

# **PARQUET**

In [79]:
df_parquet=df_pickle
print(df_parquet)

       Name  Marks
0    Aastik     85
1  Abhiyank     88
2    Ishika     91
3     Disha     99
4   Harshit    100

In [80]:
df_parquet.to_parquet("student_ppt.parquet",index=False)
#read the parquet file
df_parquet_file=pd.read_parquet("student_ppt.parquet")
print(df_parquet_file)

       Name  Marks
0    Aastik     85
1  Abhiyank     88
2    Ishika     91
3     Disha     99
4   Harshit    100

# **SQLITE**

In [88]:
import sqlite3
conn=sqlite3.connect("stduents.db")

In [89]:
cursor=conn.cursor()
print("DataBase Created Successfully")
cursor.execute("DROP TABLE IF EXISTS student_table")

DataBase Created Successfully

In [90]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS student_table(
NAME TEXT,
ROLL_NO INTEGER,
MARKS INTEGER)
"""
)
print("TABLE IS CREATED SUCCESSFULLY!!")

TABLE IS CREATED SUCCESSFULLY!!

In [91]:
#WRITE THE DATA INTO TABLE
cursor.execute(
    "INSERT INTO student_table VALUES(?, ?, ?)",
    ("Aastik",1,99)
)
cursor.execute(
    "INSERT INTO student_table VALUES('Disha',14,99)",

)

In [92]:
conn.commit()
print("Recordes inserted succesfully!!")
conn.close()

Recordes inserted succesfully!!

In [93]:
#retrive|read the data
conn=sqlite3.connect("stduents.db")
cursor=conn.cursor()
cursor.execute("SELECT * FROM student_table")
rows=cursor.fetchall()
for row in rows:
  print(row)
conn.close()

('Aastik', 1, 99)
('Disha', 14, 99)

In [87]:
import sqlite3


conn = sqlite3.connect("stduents.db")
cursor = conn.cursor()


cursor.execute("DROP TABLE IF EXISTS student_table")


cursor.execute("""
CREATE TABLE student_table(
    NAME TEXT,
    ROLL_NO INTEGER,
    MARKS INTEGER
)
""")


cursor.execute("INSERT INTO student_table VALUES(?, ?, ?)", ("Aastik", 1, 99))
cursor.execute("INSERT INTO student_table VALUES('Disha', 14, 99)")
cursor.execute("INSERT INTO student_table VALUES('Harshit', 18, 100)")

conn.commit()


cursor.execute("SELECT * FROM student_table")
for row in cursor.fetchall():
    print(row)

conn.close()

('Aastik', 1, 99)
('Disha', 14, 99)
('Harshit', 18, 100)

# **END OF DATA LOADING AND FILE STORAGE**